### ISSUE TITLE
Error when running php artisan route:pretty

### ISSUE THREAD

**Issue by MaximeGratens** [Wulfheart/pretty-routes#4] opened 2021-04-28 18:35 UTC
When trying to run `php artisan route:pretty `, I get this error :
` ErrorException

  Undefined array key 0

  at vendor/laravel/framework/src/Illuminate/Routing/Router.php:1286
    1282▕         if ($method === 'middleware') {
    1283▕             return (new RouteRegistrar($this))->attribute($method, is_array($parameters[0]) ? $parameters[0] : $parameters);
    1284▕         }
    1285▕
  ➜ 1286▕         return (new RouteRegistrar($this))->attribute($method, $parameters[0]);
    1287▕     }
    1288▕ }
    1289▕

      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
`

My project use Laravel 8.5.9

**Comment by Wulfheart** [comment] 2021-04-28 19:15
What do your routes files say? Do you maybe have a repo I can fork and try to reproduce it?

**Comment by mattstauffer** [comment] 2021-04-29 00:41
Same error here on the first project I added it to. Gonna try to see how easy it is to dig into it :)

I don't have a repo you can fork, but I'll see if I can find the source in a few minutes. Or a simplified test case.

Laravel 8.21.0.

**Comment by mattstauffer** [comment] 2021-04-29 00:44
Ahhh--here's something.  If you're running PHP 7.4, the only branch Composer will give you use `dev-tests`, rather than one of the tags, which all require PHP 8.

**Comment by mattstauffer** [comment] 2021-04-29 00:46
Just kidding. Sorry. Error still there in release 0.1.2, PHP 8. Separate problem. Will refrain from further comments until I can find the source of this actual problem.

**Comment by mattstauffer** [comment] 2021-04-29 01:01
Looks like the issue is that the pretty routes command is calling `flushMiddlewareGroups()` which wasn't added until Laravel 8.28.0.

**Comment by Gummibeer** [comment] 2021-04-29 07:28
Fixed by #10

**Closed as completed by Gummibeer** 2021-04-29 07:28 UTC
Labels: bug
