### ISSUE TITLE
-d --update-snapshots flag is needed for the phpunit tests to work

### ISSUE THREAD

**Issue by bhushan** [Wulfheart/pretty-routes#17] opened 2021-04-29 20:28 UTC
<img width="1386" alt="Screenshot 2021-04-30 at 1 52 17 AM" src="https://user-images.githubusercontent.com/43483545/116613915-e0e02680-a956-11eb-8911-c3da2122cf2b.png">

If a new contributor forks the project and runs the tests .. then it fails .. and it suggests adding `-d --update-snapshots` flag with the PHP unit command.. then tests works fine.

but the problem is snapshots output file is modified and then it will be part of new PR. SO each new PR will have its own snapshot version.

**Comment by Wulfheart** [comment] 2021-04-29 20:35
Did you fork the current master? @Gummibeer added in #12 an additiona env variable for this.

**Comment by bhushan** [comment] 2021-04-29 20:40
yes just before some time. I thought of working on that filter route feature.. but faced this.

**Comment by Wulfheart** [comment] 2021-04-29 20:44
Try merging the current master branch. This should(!) do the trick,

**Comment by bhushan** [comment] 2021-04-29 20:45
<img width="1375" alt="Screenshot 2021-04-30 at 2 11 59 AM" src="https://user-images.githubusercontent.com/43483545/116616075-d5422f00-a959-11eb-91df-8289f962bfab.png">


took pull again

**Comment by Wulfheart** [comment] 2021-04-29 20:47
So this can be closed now?

**Comment by bhushan** [comment] 2021-04-29 20:50
No, What I meant was I took pull again .. even forked it again.. still facing the same thing

**Comment by Wulfheart** [comment] 2021-04-29 20:52
Oh. Not good. @Gummibeer any idea?

**Comment by Gummibeer** [comment] 2021-04-29 21:40
I'm unable to reproduce - I've tried it with different terminals on different machines and resized them a lot, all tests passed every time.
@bhushan you've pulled from your own `master` branch. Could you pull from the base master branch?

```bash
git pull https://github.com/Wulfheart/pretty-routes.git master
```

**Comment by bhushan** [comment] 2021-04-30 10:12
Actually, I forked it again by deleting the previous fork.. so it should have the latest changes. Still checking it once again for surity.

**Comment by bhushan** [comment] 2021-04-30 10:13
<img width="1375" alt="Screenshot 2021-04-30 at 3 42 57 PM" src="https://user-images.githubusercontent.com/43483545/116681549-be87f080-a9ca-11eb-9e56-de63626c0c7e.png">

I still see the problem @Gummibeer

**Comment by Gummibeer** [comment] 2021-04-30 11:35
But only one test - could it be that different terminals use different ansi codes. 🤔
It's not the width failing now - or at least it doesn't seem like as the base output test passes.
Could you comment what your updated snapshot would look like?

**Comment by bhushan** [comment] 2021-04-30 16:39
[32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1m/[39;22m[38;2;108;114;128m .......................................................................................... [39m
  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1madmin[39;22m[38;2;108;114;128m ...................................................................................... [39m
  [35mPOST[39m           [37;1msome/thing/[39;22m[33m{one?}[39m[37;1m/[39;22m[33m{two}[39m[37;1m/some/[39;22m[33m{three?}[39m[38;2;108;114;128m ...................................................... [39m
  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1mtest[39;22m[38;2;108;114;128m ............................................................................ [39mtest.index
  [35mPOST[39m           [37;1mtest[39;22m[38;2;108;114;128m ............................................................................ [39mtest.store
  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1mtest/create[39;22m[38;2;108;114;128m .................................................................... [39mtest.create
  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1mtest/[39;22m[33m{test}[39m[38;2;108;114;128m ...................................................................... [39mtest.show
  [33mPUT[39m[37;1m|[39;22m[33mPATCH[39m      [37;1mtest/[39;22m[33m{test}[39m[38;2;108;114;128m .................................................................... [39mtest.update
  [31mDELETE[39m         [37;1mtest/[39;22m[33m{test}[39m[38;2;108;114;128m ................................................................... [39mtest.destroy
  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1mtest/[39;22m[33m{test}[39m[37;1m/edit[39;22m[38;2;108;114;128m ................................................................. [39mtest.edit
  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [33m{one?}[39m[37;1m/[39;22m[33m{two}[39m[37;1m/some/[39;22m[33m{three?}[39m[38;2;108;114;128m ................................................................. [39m

**Comment by bhushan** [comment] 2021-04-30 16:39
[SnapshotTest__ansi_output__1.txt](https://github.com/Wulfheart/pretty-routes/files/6406810/SnapshotTest__ansi_output__1.txt)

**Comment by bhushan** [comment] 2021-05-01 04:52
I dont think so terminals has different ansi codes but still JFI I have macbook pro ratina display, i use iterm with zsh, (oh my zsh).

in the screenshots. That is phpstorm terminal..

its 16inch display .. may be you get terminal width idea from this

**Comment by Gummibeer** [comment] 2021-05-01 10:13
It's different ansi codes (or however they are named).
current snapshot `[34m`
@bhushan snapshot `[38;2;108;114;128m`

```diff
diff --git a/tests/__snapshots__/SnapshotTest__ansi_output__1.txt b/tests/__snapshots__/SnapshotTest__ansi_output__1.txt
index 1af285a..3d21f3b 100644
--- a/tests/__snapshots__/SnapshotTest__ansi_output__1.txt
+++ b/tests/__snapshots__/SnapshotTest__ansi_output__1.txt
@@ -1,11 +1,11 @@
-  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1m/[39;22m[34m .......................................................................................... [39m
+  [32mGET[39m[37;1m|[39;22m[39mHEAD[39m       [37;1m/[39;22m[38;2;108;114;128m .......................................................................................... [39m
```

**Comment by Gummibeer** [comment] 2021-05-01 10:14
So seems like testing the ansi formatting with snapshot tests is a bad idea. Instead it should test what is thrown into the symfony output formatter. So like `<fg=red>` - this is always the same.

**Comment by bhushan** [comment] 2021-05-01 11:13
Output formatter seems nice idea ..

**Comment by Wulfheart** [comment] 2021-05-03 09:31
The tests are currently still failing in Github Actions and I have still no idea why. Therefore I tested it manually on my machine.

**Comment by bhushan** [comment] 2021-05-03 14:59
Anyone working on this issue? I will be having busy schedule this week.. If it doesn't gets fixed till then then i will share PRs on Saturday may be.

**Comment by bhushan** [comment] 2021-05-03 15:00
@Gummibeer Tom are you on to it ?

**Comment by Gummibeer** [comment] 2021-05-03 15:38
Nope, I'm not on it.

**Comment by bhushan** [comment] 2021-05-03 19:41
@mattstauffer @Gummibeer How can i get output formatter in tests?

**Comment by mattstauffer** [comment] 2021-06-14 17:59
Can you use the artisan expects?

https://www.csrhymes.com/2021/01/31/testing-a-laravel-console-command.html

I don't know if that works in a package.

**Comment by Wulfheart** [comment] 2022-01-19 19:54
Closing as the Laravel 9 will support the command natively as per [this PR](https://github.com/laravel/framework/pull/40269).

**Closed as completed by Wulfheart** 2022-01-19 19:54 UTC
